version: "3.7"

services:
  bot:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: ${PROJECT_NAME}
    container_name: "${PROJECT_NAME}"
    environment:
      - TOKEN
      - APPLICATION_ID
      - DEFAULT_GUILD_ID
      - OWNER_ID
      - ADMINS_ID
      - DB_HOST
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
